version: '3.8'

services:
  db:
    image: timescale/timescaledb-oss:latest-pg16
    restart: always
    environment:
      POSTGRES_DB: stockpick_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: stockpick_db
      PORT: 8080
      FMP_API_KEY: ${FMP_API_KEY} # Placeholder for FMP API Key
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80" # React development server or Nginx serving static files
    depends_on:
      - backend

volumes:
  db_data: